{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "repo-audit.secretname" . }}
  labels:
    app.kubernetes.io/name: {{ include "repo-audit.name" . }}
    helm.sh/chart: {{ include "repo-audit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  config.json: {{ .Values.config | toJson | b64enc | quote }}
{{- end }}